config/routes.rb
Rails.application.routes.draw do
  resources :characters
  root "characters#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
    @character.randomize
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to character_url(@character), notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_url(@character), notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:name, :age, :gender, :race, :jobclass, :alignment, :personality, :mainquality, :mainfault, :haircolor, :eyescolor, :signs, :past, :dream)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="input-group input-group-lg form-start-point">
    <span class="input-group-text" id="inputGroup-sizing-lg">Nom du personnage</span>
    <%= form.text_field :name, class:"form-control form-control-lg", placeholder:"Écrire ici..." %>
  </div>

  <div class="allforms">
    <section class="leftform">
      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Âge</span>
        <%= form.text_field :age, class:"form-control form-control-lg" %>
      </div>

      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Genre</span>
        <%= form.text_field :gender, class:"form-control form-control-lg" %>
      </div>

      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Race</span>
        <%= form.text_field :race, class:"form-control form-control-lg" %>
      </div>

      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Classe de personnage</span>
        <%= form.text_field :jobclass, class:"form-control form-control-lg" %>
      </div>

      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Alignement</span>
        <%= form.text_field :alignment, class:"form-control form-control-lg" %>
      </div>
    </section>

    <section class="rightform">
      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Personnalité (MBTI)</span>
        <%= form.text_field :personality, class:"form-control form-control-lg" %>
      </div>

      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Principale qualité</span>
        <%= form.text_field :mainquality, class:"form-control form-control-lg" %>
      </div>

      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Principal défaut</span>
        <%= form.text_field :mainfault, class:"form-control form-control-lg" %>
      </div>

      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Couleur de cheveux</span>
        <%= form.text_field :haircolor, class:"form-control form-control-lg" %>
      </div>

      <div class="input-group input-group-lg">
        <span class="input-group-text" id="inputGroup-sizing-lg">Couleur des yeux</span>
        <%= form.text_field :eyescolor, class:"form-control form-control-lg" %>
      </div>
    </section>
  </div>

  <div class="input-group input-group-lg">
    <span class="input-group-text" id="inputGroup-sizing-lg">Signe(s) distinctif(s)</span>
    <%= form.text_field :signs, class:"form-control form-control-lg" %>
  </div>

  <div class="input-group input-group-lg">
    <span class="input-group-text" id="inputGroup-sizing-lg">Passé</span>
    <%= form.text_field :past, class:"form-control form-control-lg" %>
  </div>

  <div class="input-group input-group-lg">
    <span class="input-group-text" id="inputGroup-sizing-lg">Rêve/Objectif</span>
    <%= form.text_field :dream, class:"form-control form-control-lg" %>
  </div>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/_header.html.erb
<nav class="navbar">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  </div>
</nav>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>


<table class="table">
  <thead class="table-dark">
    <tr>
      <th>Nom du personnage</th>
      <th>Âge</th>
      <th>Genre</th>
      <th>Race</th>
      <th>Classe</th>
      <th>Alignement</th>
      <th>Personalité MBTI</th>
      <th>Principale qualité</th>
      <th>Principal défaut</th>
      <th>Couleur des cheveux</th>
      <th>Couleur des yeux</th>
      <th>Signes distinctifs</th>
      <th>Passé</th>
      <th>Rêve</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @characters.each do |character| %>
      <div class="jumbotron">
        <h1 class="display-4"><%= character.name %></h1>
        <h2><%= character.age %> ans</h2>
        <h3><%= character.race %> <%= character.gender %></h3>
        <hr class="my-4">
        <p><b>Alignement :</b><%= character.alignment %></p>
        <p><b>Personalité (MBTI) :</b><%= character.personality %></p>
        <p><b>Principale qualité :</b><%= character.mainquality %></p>
        <p><b>Principal défaut :</b><%= character.mainfault %></p>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </p>
      </div>
    <% end %>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.age %></td>
        <td><%= character.gender %></td>
        <td><%= character.race %></td>
        <td><%= character.jobclass %></td>
        <td><%= character.alignment %></td>
        <td><%= character.personality %></td>
        <td><%= character.mainquality %></td>
        <td><%= character.mainfault %></td>
        <td><%= character.haircolor %></td>
        <td><%= character.eyescolor %></td>
        <td><%= character.signs %></td>
        <td><%= character.past %></td>
        <td><%= character.dream %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character), class:"btn btn-primary btn-lg" %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary btn-lg" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path, class:"btn btn-primary btn-lg" %>

app/views/characters/new.html.erb
<div class="centercontainer">
  <div class="randomize-button"><a href="" href="#form-start-point"><img src="https://cdn.discordapp.com/attachments/495991546928431116/959431671176908900/Group_3.png" alt="Générer un personnage"></a></div>
</div>

<%= render 'form', character: @character %>

<%# <%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @character.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @character.gender %>
</p>

<p>
  <strong>Race:</strong>
  <%= @character.race %>
</p>

<p>
  <strong>Jobclass:</strong>
  <%= @character.jobclass %>
</p>

<p>
  <strong>Alignment:</strong>
  <%= @character.alignment %>
</p>

<p>
  <strong>Personality:</strong>
  <%= @character.personality %>
</p>

<p>
  <strong>Mainquality:</strong>
  <%= @character.mainquality %>
</p>

<p>
  <strong>Mainfault:</strong>
  <%= @character.mainfault %>
</p>

<p>
  <strong>Haircolor:</strong>
  <%= @character.haircolor %>
</p>

<p>
  <strong>Eyescolor:</strong>
  <%= @character.eyescolor %>
</p>

<p>
  <strong>Signs:</strong>
  <%= @character.signs %>
</p>

<p>
  <strong>Past:</strong>
  <%= @character.past %>
</p>

<p>
  <strong>Dream:</strong>
  <%= @character.dream %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>